title: Adam Kells
author:
  name: adamkells
  email: adamjkells93@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  I'm trying to build cool stuff with data.
# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: emperor
  social_links:
    - { platform: github,   user_url: "https://github.com/adamkells" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/adam-kells" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - about.md
  - blog.md
  - favourites.md
  - links.md
  - research.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
